---
abstract: 'An incubator for Perls in the Cloud'
author:
  - 'osfameron <osfameron@cpan.org>'
build_requires:
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Oyster
requires:
  Carp: 0
  Catalyst::Helper: 0
  Config::Any: 0
  Data::Dumper: 0
  Dist::Zilla::App: 0
  Dist::Zilla::File::FromCode: 0
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::ModuleMaker: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Error::Simple: 0
  File::Copy: 0
  File::ShareDir: 0
  Git::Wrapper: 0
  MIME::Base64: 0
  Moose: 0
  Moose::Role: 0
  Net::Amazon::EC2: 0
  Net::RackSpace::CloudServers: 0
  Net::RackSpace::CloudServers::Server: 0
version: 0.001
